# This file contains values from Cookiecutter

default_context:
  project_name: "ctxt2d"
  project_description: "Compares text in a file to reference/glossary/key-items/dictionary file."
  organization: "ctxt2d"
  license: "MIT"
  minimal_python_version: 3.9
  github_name: "davidprush"
  email: "davidprush@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "none"
